version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app 
      - nas_uploads:/var/www/uploads 
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=nas_user
      - MYSQL_PASSWORD=supersecretpassword
      - MYSQL_DB=nas_web
      - UPLOAD_FOLDER=/var/www/uploads
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    depends_on:
      - db
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootsecretpassword
      - MYSQL_DATABASE=nas_web
      - MYSQL_USER=nas_user
      - MYSQL_PASSWORD=supersecretpassword
    volumes:
      - nas_db_data:/var/lib/mysql
volumes:
  nas_db_data:
  nas_uploads:
